# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add vector through a matrix
#' 
#' @param A - matrix ( explain what this is)
#' @param b - vector ( explain what this is)
#' @export
addMatVec <- function(A, b) {
    .Call('_PRISM_addMatVec', PACKAGE = 'PRISM', A, b)
}

#' Add matrix through a matrix
#' 
#' @param A - matrix ( explain what this is)
#' @param B - vector ( explain what this is)
#' @export
addMatMat <- function(A, B) {
    .Call('_PRISM_addMatMat', PACKAGE = 'PRISM', A, B)
}

#' For a vector y of length yT, return a (1-based) vector where entry i counts the number of times integer i-1 was seen in the data
#' 
#' @param y vector of integers
#' @param yT length of y
#' @param xT maxmimum integer to count to
#' @export
increment <- function(y, yT, xT) {
    .Call('_PRISM_increment', PACKAGE = 'PRISM', y, yT, xT)
}

#' For a vector y of length yT, return a (1-based) vector where entry i counts the number of times integer i-1 was seen in the data
#' 
#' @param y vector of integers
#' @param yT length of y
#' @param xT maxmimum integer to count to
#' @export
increment2N <- function(y, z, yT, xT) {
    .Call('_PRISM_increment2N', PACKAGE = 'PRISM', y, z, yT, xT)
}

